travis:
  secure:
    BINSTAR_TOKEN: R9TS0BznBMB8fHiTWeR0WeWxeI2TICrynI7vYjkh85CAFVJOqtSAzEAd2VQN7uMvehpLfeHoDoGH4ERaOsOVcDdrtcXhePq5piJOC6/vclyIde6AoETv/DtfnnV5GvSCuHG42TGCjiJ7nEohh0ndIRNmqxHAuRtUr/d2FUFLYJzuHHuzA2j4F6gfLn8QKstAMvim4DUqiPOvzQYUxX5L+E3PoH4xReGeG78l+cyKwiQs3avnupyLpavRVC9vkISSnBHkyfoMD3YA8wO+jKC9bYg9hhco/rL2VS0skZTWE4muy6Uh4hbdxVBv1EFLI4o+MQr3f9X7s1/lrKowzqHXXi0DHU7GKeiZlt6EbGGb8FMc1fR34AWUwTZcdOM80Yq2UoBd2+w+Nxz5JmA9JS/b/heJlYRG0RqwfG0+8XkepW7kCSu0VwBomciCqHmXDv2PBGMl0OFItEnOYBX6Sy4ZxG/AOcRSzFvcnMenae9Vqz6txrkkGFcqzNS/biLKemcLPFvNlixmYLCc3MArHgdoQFjtUCaIbcVf6br1oKUqm0zWocoYNtprMnO30AS2HxcuqNcYZWOPDAJWvxbSSSazgxsz50EW62qvDD7YwgsEb4llQGVCQG3+Zbk9jOZ/rrXhUT1KbMuKKQCUlPsg9aS+7wfVVinoxYRpxfWIfn8KHCI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
